galaxy_info:
  author: Daniel Andrei Minca
  description: Provision Fedora machines with Docker Engine
  company: Open-Source
  issue_tracker_url: https://github.com/WizDevOps/containerschiff/issues
  license: GPLv3
  min_ansible_version: 2.4
  github_branch: fedora
  platforms:
    - name: Fedora
      versions:
        - 27
  galaxy_tags:
    - docker
    - fedora
dependencies: []
