---
- name: Copy the dotfiles to home dir
  copy: src={{ item }} dest=~/
  with_items:
    - .bash_aliases
    - .bash_formatting
    - .bashrc
    - .gemrc
    - .git-commit-template.commit
    - .taskrc
    - .tmux.conf
  tags: dotfiles

- name: Add the gitconfig with custom User and Email
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
  tags: dotfiles
