---
- name: Copy the dotfiles to home dir
  copy: src={{ item }} dest=~/
  with_items:
    - .bash_aliases
    - .bash_formatting
    - .bashrc
    - .gemrc
    - .git-commit-template.commit
    - .gitconfig
    - .taskrc
    - .tmux.conf
    - .vimrc
  tags: dotfiles
