---
- name: Copy the dotfiles to home dir
  copy: src={{ item }} dest=~/
  with_items:
    - .bash_aliases
    - .bash_formatting
    - .bashrc
    - .gemrc
    - .git-commit-template.commit
    - .taskrc
    - .tmux.conf

- name: create gnupg directory
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700

- name: add gpg configuration file
  template:
    src: gpg.conf.j2
    dest: ~/.gnupg/gpg.conf
    mode: 0700

- name: Add the gitconfig with custom User and Email
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: make sure openbox exists
  file:
    path: ~/.config/openbox/
    state: directory
    mode: 0775

- name: check if openbox installed
  command: 'openbox --version'
  ignore_errors: true
  register: obox

- name: enable openbox keyboard shortcuts
  template:
    src: lxde-rc.xml.j2
    dest: ~/.config/openbox/lxde-rc.xml
    mode: 0644
  notify: reload openbox
  when: obox.rc == 0

- name: ensure git directories are created
  file:
    path: "{{ ansible_env.HOME}}/Repos/{{ item }}"
    state: directory
  with_items:
    - work
    - open-source

- name: Add the gitconfig with custom User and Email
  template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.{{ item.dest }}"
  with_items:
    - { src: gitconfig.j2, dest: gitconfig }
    - { src: gitconfig_open_source.j2, dest: gitconfig_open_source }
    - { src: gitconfig_work.j2, dest: gitconfig_work }
