---
- name: download telegram via telegram.org
  get_url:
    url: https://telegram.org/dl/desktop/linux
    dest: /tmp/tsetup.tar.xz
    force: no
  register: telegram_archive

- name: create app dir
  file:
    path: /opt/telegram
    state: directory
    mode: 0755

- name: extract archive to app dir
  unarchive:
    src: /tmp/tsetup.tar.xz
    dest: /opt/telegram
    copy: no
  when: telegram_archive | changed
