---
- name: create app dir
  become: true
  become_method: sudo
  file:
    path: /opt/telegram
    state: directory
    mode: 0755
    owner: "{{ ansible_user_id }}"
    group: users

- name: extract archive to app dir
  become: true
  become_method: sudo
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: /opt/telegram
    owner: "{{ ansible_user_id }}"
    group: users
    remote_src: true
    validate_certs: false

