---
- name: Make directories for vim-pathogen
  file: 
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - bundle
    - syntax

- name: Pull vim-pathogen and nginx syntax
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.vim/{{ item.dest }}"
    force: no
  with_items:
    - { url: "https://tpo.pe/pathogen.vim", dest: autoload }
    - { url: "https://raw.githubusercontent.com/nginx/nginx/master/contrib/vim/syntax/nginx.vim", dest: syntax }

- name: Install vim plugins
  git:
    repo: https://github.com/{{ item.name }}
    dest: "{{ ansible_env.HOME }}/.vim/bundle/{{ item.dir }}"
    update: no
    force: no
  with_items:
    - { name: scrooloose/nerdtree.git, dir: nerdtree.vim }
    - { name: MarcWeber/vim-addon-mw-utils.git, dir: vim-addon-mw-utils }
    - { name: kien/ctrlp.vim.git, dir: ctrlp.vim }
    - { name: dyng/ctrlsf.vim.git, dir: ctrlsf.vim }
    - { name: terryma/vim-multiple-cursors.git, dir: vim-multiple-cursors }

- name: deploy custom vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"

