---
- name: Install Zsh from official repo
  become: yes
  become_method: sudo
  shell: >
    curl -sSL http://install.ohmyz.sh | sh -s
  tags: zsh

- name: Pull the Custom Plugins and Themes
  get_url:
    url: https://raw.githubusercontent.com/{{ gh_user }}/{{ gh_repo }}/{{ gh_branch }}/custom/{{ item.name }}
    dest: ~/.oh-my-zsh/custom/{{ item.dir }}
  with_items:
    - { name: 'plugins/dangit/dangit.plugin.zsh', dir: 'plugins/dangit/'}
    - { name: 'themes/danthe.zsh-theme', dir: 'themes/'}
  tags: zsh

- name: Remove default .zshrc
  file: path=~/.zshrc state=absent
  tags: zsh

- name: Deploy customized .zshrc
  copy: src=.zshrc dest=~/
  tags: zsh

- name: Set zsh as default shell
  user: name=$user shell=/bin/zsh
  tags: zsh
