---
- name: Install Zsh from official repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    update: no

- name: Set zsh config dir permissions
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    owner: "{{ ansible_user_id }}"
    group: users
    recurse: yes

- name: Set zsh as default shell
  become: yes
  become_method: sudo
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Create plugins and themes dirs
  file: 
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item }}" 
    state: directory
  with_items:
    - plugins/dangit
    - themes

- name: Pull the Custom Plugins and Themes
  get_url:
    url: "https://raw.githubusercontent.com/{{ git.username }}/{{ git.repo }}/{{ git.branch }}/custom/{{ item.name }}"
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/{{ item.dir }}"
    mode: 0644
  with_items:
    - { name: 'plugins/dangit/dangit.plugin.zsh', dir: 'plugins/dangit/'}
    - { name: 'themes/danthe.zsh-theme', dir: 'themes/'}

- name: Deploy customized .zshrc
  copy: 
    src: .zshrc
    dest: "{{ ansible_env.HOME }}"
    force: yes

