---
- name: Install Zsh from official repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /home/$USER/.oh-my-zsh
    update: no
  tags: zsh

- name: Set zsh config dir permissions
  file:
    path: /home/$USER/.oh-my-zsh
    owner: $USER
    group: $USER
    recurse: yes
  tags: zsh

- name: Set zsh as default shell
  user:
    name: $USER
    shell: which zsh
  tags: zsh

- name: Pull the Custom Plugins and Themes
  become: yes
  become_method: sudo
  get_url:
    url: https://raw.githubusercontent.com/{{ gh_user }}/{{ gh_repo }}/{{ gh_branch }}/custom/{{ item.name }}
    dest: ~/.oh-my-zsh/custom/{{ item.dir }}
    mode: 0644
  with_items:
    - { name: 'plugins/dangit/dangit.plugin.zsh', dir: 'plugins/dangit/'}
    - { name: 'themes/danthe.zsh-theme', dir: 'themes/'}
  tags: zsh

# - name: Remove default .zshrc
#   file: path=~/.zshrc state=absent
#   tags: zsh

- name: Deploy customized .zshrc
  copy: src=.zshrc dest=~/
  tags: zsh
