web:
  image: completit/dockerized-drupal:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - {{ playbook_dir }}/roles/drupal/app:/var/www/html
  working_dir: /var/www/html
  links:
    - psql

psql:
  image: kiasaki/alpine-postgres
  environment:
    - POSTGRES_PASSWORD=drupal
    - POSTGRES_USER=drupal
    - POSTGRES_DB=drupal
  volumes:
    - {{ playbook_dir }}/roles/drupal/db:/var/lib/postgresql/data
  # ports:
  #   - "5432:5432"
