---
- name: Create the font config dir
  file:
    path: ~/.fonts/truetype
    state: directory

- name: copy the font to dir
  copy:
    src: consolas.ttf
    dest: "{{ ansible_env.HOME }}/.fonts/truetype/Consolas.ttf"
  notify: clear font cache

