---
- name: Install the Microsoft TrueType fonts
  become: yes
  become_method: sudo
  pacman:
    name: ttf-ms-fonts
    state: latest
    update_cache: yes

- name: Create the font config dir
  file:
    path: ~/.fonts/truetype/Hack
    state: directory

- name: Download the font archive
  get_url:
    url: https://github.com/chrissimpkins/Hack/releases/download/v2.020/Hack-v2_020-ttf.tar.gz
    dest: /tmp

- name: Extract the archive
  unarchive:
    src: /tmp/Hack-v2_020-ttf.tar.gz
    dest: ~/.fonts/truetype/Hack

- name: Clear teh font cache
  become: yes
  become_method: sudo
  command: fc-cache -f
