---
- name: install dropbox package
  become: true
  become_method: sudo
  apt:
    deb: "{{ dropbox_url_deb }}"
  register: dbox_result

- name: run dropbox daemon interface
  command: dropbox start -i
  when: dbox_result | changed

