---
- name: install required packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dpkg-dev
    - virtualbox-dkms

- name: download the deb file & scan
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{ vbox_patch }}/{{ virtualbox_xenial.deb }}"
    mode: 0644
    dest: /tmp
    checksum: "sha256:{{ virtualbox_xenial.sha256 }}"

- name: download & scan ExtPack
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{ vbox_patch }}/{{ virtualbox_extpack.file }}"
    mode: 0644
    dest: /tmp
    checksum: "sha256:{{ virtualbox_extpack.sha256 }}"

- name: validate public key
  become: true
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present

- name: install virtualbox via deb file
  become: true
  apt:
    deb: "/tmp/{{ virtualbox_xenial.deb }}"
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: install the ExtPack
  command: "virtualbox /tmp/{{ virtualbox_extpack.file }}"
