---
dropbox_version: "2015.10.28"
dropbox_tmp_deb: "/tmp/dropbox_{{dropbox_version}}.deb"
dropbox_architecture: "{% if ansible_architecture == 'x86_64' %}amd64{% else %}i386{% endif %}"
dropbox_url_deb: "https://www.dropbox.com/download?dl=packages/{{ ansible_distribution|lower }}/dropbox_{{dropbox_version}}_{{dropbox_architecture}}.deb"
