---
- name: download LibreOffice5
  get_url:
    url: "http://mirrors.serverhost.ro/libreoffice/tdf/libreoffice/stable/{{ libre_version }}/deb/{{ ansible_architecture }}/LibreOffice_{{ libre_version }}_{{ ansible_system }}_x86-64_deb.tar.gz"
    dest: /tmp/libreoffice.tar.gz
    sha256sum: "{{ libre_sha256sum }}"

- name: extract archive
  unarchive:
    src: /tmp/libreoffice.tar.gz
    dest: /tmp
    exclude: 'readmes/*'

- name: list libreoffice debs
  command: "ls /tmp/LibreOffice_{{ libre_version }}.2_{{ ansible_system }}_x86-64_deb/DEBS/"
  register: libre_debs

- name: install LibreOffice5
  become: true
  become_method: sudo
  apt:
    deb: "/tmp/LibreOffice_{{ libre_version }}.2_{{ ansible_system }}_x86-64_deb/DEBS/{{ item.1 }}"
  with_indexed_items: 
    - "{{ libre_debs.stdout_lines[44] }}"
    - "{{ libre_debs.stdout_lines[2] }}"
    - "{{ libre_debs.stdout_lines[22] }}"
    - "{{ libre_debs.stdout_lines[33] }}"
    - "{{ libre_debs.stdout_lines }}"

- name: teardown after install
  file:
    path: "/tmp/{{ item }}"
    state: absent
  with_items:
    - "libreoffice.tar.gz"
    - "LibreOffice_{{ libre_version }}.2_{{ ansible_system }}_x86-64_deb"
