---
- name: restart network
  become: true
  systemd:
    unit: NetworkManager
    state: reloaded

- name: start bond
  become: true
  command: netctl start bond0
  notify: enable bond

- name: enable bond
  become: true
  command: netctl enable bond0
  notify: switch to bond

- name: switch to bond
  become: true
  command: netctl switch-to bond0
