---
# tasks file for debian-vagrant
- name: download and scan vagrant package
  get_url:
    url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.deb"
    mode: 0644
    dest: /tmp
    checksum: "sha256:{{ vagrant_sha256 }}"

- name: install dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dpkg-dev
    - virtualbox-dkms

- name: unpack the deb
  become: true
  apt:
    deb: "/tmp/vagrant_{{ vagrant_version }}_x86_64.deb"