---
- name: Create sublime config folder
  file: 
    path: ~/.config/sublime-text-3/Packages/User/
    state: directory

- name: Copy the User configurations
  copy: 
    src: "{{ item }}" 
    dest: '~/.config/sublime-text-3/Packages/User'
    force: no
  with_items:
    - bash.sublime-snippet
    - bash-subtitle.sublime-snippet
    - Default (Linux).sublime-keymap
    - Preferences.sublime-settings
    - Package Control.sublime-settings

- name: Create the Installed Packages dir
  file:
    path: '~/.config/sublime-text-3/Installed Packages'
    state: directory

