---
- name: Create sublime config folder
  file: 
    path: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/"
    state: directory

- name: Copy the User configurations
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/{{ item }}"
  with_items:
    - bash.sublime-snippet
    - bash-subtitle.sublime-snippet
    - Default (Linux).sublime-keymap
    - Preferences.sublime-settings
    - Python.sublime-settings

- name: Create the Installed Packages dir
  file:
    path: "{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages"
    state: directory

