---
- name: Download Sublime Text
  become: yes
  become_method: sudo
  get_url:
    url: http://c758482.r82.cf2.rackcdn.com/{{ sublime_debfile }}
    dest: /tmp
    force: no

- name: Install sublime deb
  become: yes
  become_method: sudo
  apt: 
    deb: "/tmp/{{ sublime_debfile }}"