---
# sublime text 3 main task
- name: check if sublime already installed
  apt:
    name: sublime-text=3065
    state: present
  register: subl # now I can use [when: subl.changed is false]

- include: install.yml
  when: subl.changed is not false
- include: configure.yml
  when: subl.changed is not false
