---
# sublime text 3 task
# Download sublime text 3 {{ sublime_version }}.deb
- name: Download Sublime Text
  become: yes
  become_method: sudo
  get_url:
    url: http://c758482.r82.cf2.rackcdn.com/{{ sublime_debfile }}
    dest: /tmp
  tags: subl_install

# install {{ sublime_version }}.deb
- name: Install sublime deb
  become: yes
  become_method: sudo
  shell: dpkg -i /tmp/{{ sublime_debfile }}
  tags: subl_install

- name: Download Sublime 3 executable
  get_url:
    url: http://cl.ly/1z0S25150Y0I/sublime_text%20crack%20linux%2064%20build%203065
    dest: /opt/sublime_text/sublime_text
    mode: 0755
  tags: subl_install

- name: Copy the User configurations
  copy: src={{ item }} dest='~/.config/sublime-text-3/Packages/User'
  with_items:
    - bash.sublime-snippet
    - bash-subtitle.sublime-snippet
    - Default (Linux).sublime-keymap
    - Preferences.sublime-settings
    - Package Control.sublime-settings
  tags: subl_install

- name: Cleanup after installation
  become: yes
  become_method: sudo
  file: path=/tmp/{{ sublime_debfile }} state=absent
  tags: subl_install
