---
- name: install the docker suite
  pacman: 
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - docker
    - docker-compose
    - docker-machine

- name: start and enable docker engine
  become: true
  systemd:
    name: docker
    state: started
    enabled: true

